### ISSUE TITLE
Decoding single channel image

### ISSUE THREAD

**Issue by namse** [image-rs/image-webp#108]
Hello, I tried to encode Luma8 without an Alpha channel losslessly, then decode it to obtain channel data equivalent to width * height bytes. However, contrary to my expectations, the decoder seems to output only in RGB or RGBA formats. Is there any way to get just a single channel as the result of decoding?

**Comment by fintelia** [comment]
This is a limitation of the webp file format. There actually isn't a way to indicate that an image is grayscale, so the behind the scenes the encoder stores Luma8 images as Rgb8.
