### ISSUE TITLE
WebP corruption issue: lossless RGB or lossy RGBA images are not supported.

### ISSUE THREAD

**Issue by rohitmittapalli** [image-rs/image-webp#113]
Prior to this change:https://github.com/image-rs/image/pull/2148 image-rs use the `webp` crate. This supported loss and lossless. 

Looks like switching over to image-rs/image-webp we lost our ability to support lossless RGB and lossy RGBA images.

/// WebP Image format decoder. Currently only supports lossy RGB images or lossless RGBA images based on this [comment](https://github.com/image-rs/image/blob/9489d7167f18d5a49b87c94ddd60343635fc4e5a/src/codecs/webp/decoder.rs#L8). The docs do not reflect this.

**Comment by fintelia** [comment]
Confirmed that this is a bug in `image_webp`. Image is corrupt due to missing color cache update.

Thanks for the report!

<img src="https://github.com/user-attachments/assets/4b78f118-1532-4562-81a1-fd28efc2f817" width="250">

**Comment by rohitmittapalli** [comment]
@fintelia thank you for the incredibly fast fix! any chance we can cut a new release for this? have a bug this would fix :)

**Comment by fintelia** [comment]
Will prioritize getting out releases. Both `image-webp` and `image` will have to release new versions due to other breaking changes that landed in earlier PRs

**Comment by rohitmittapalli** [comment]
Thank you, this is greatly appreciated!

**Comment by fintelia** [comment]
New versions of both crates have now been published!
