### ISSUE TITLE
Add odd-width/odd-dimensioned lossy pixel tests and images

### ISSUE THREAD

**Issue by okaneco** [image-rs/image-webp#12]
I noticed that all of the lossy reference images had even dimensions. I wasn't sure what the process was for adding new test images.

I wrote code that incorrectly handled some end pixels in rows but passed all the tests. I created these two tests to check that my function matched the current `fill_single` implementation. The 3x3 test is what my code failed at first since I was handling 2 pixels at a time due to the chroma plane.
https://github.com/okaneco/image-webp/commit/0f96c2efbd6037eac741b6c5a4fc4398ca11add5

**Comment by fintelia** [comment]
The existing images are all from https://developers.google.com/speed/webp/gallery. The structure is the webp file is in `tests/images/` and an equivalent PNG decoded with "-nofancy" in `tests/reference/`. I should really add a README to the tests directory explaining all that...

Not sure the best way to do additional images. As far as I can tell libwebp is the only decoder in widespread use. So maybe it makes sense to feed a large number of tiny images (or cropped pieces of larger ones) with random compression parameters into that encoder and use those as a test suite?

**Comment by fintelia** [comment]
#18 added some odd-sized images and more documentation of how the tests images were obtained
