### ISSUE TITLE
Some images are decoded washed out

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-webp#54]
Tested on `image` on commit 3b1fbcf2aedb809793a49d21ee5bb62ffafa3739 (the 0.25 branch), the testing methodology is same as in https://github.com/image-rs/image/issues/1872

Original:

![dc-siamo-annuncio-breve-james-gunn-svela-progetti-presentati-v3-631174-1280x960 webp magick](https://github.com/image-rs/image-webp/assets/291257/68704178-a1c6-4e3b-89ca-dc7fc407e380)

Decoded by `image`:
![dc-siamo-annuncio-breve-james-gunn-svela-progetti-presentati-v3-631174-1280x960 webp image](https://github.com/image-rs/image-webp/assets/291257/aa6d43ef-5627-4d21-8647-ea96c04a611b)

The same thing happens with small images. 

Original:

![tr webp magick](https://github.com/image-rs/image-webp/assets/291257/f3d47014-dd44-4d3c-adf6-ea077e7568cb)

Decoded by `image`:

![tr webp image](https://github.com/image-rs/image-webp/assets/291257/0389ca74-df5a-4435-9d17-20e8d7692c71)

Color doesn't seem to be necessary:

![twitter webp magick](https://github.com/image-rs/image-webp/assets/291257/fa2ca3e4-69ad-4806-a75b-8bc49e3dd618)

gets decoded as

![twitter webp image](https://github.com/image-rs/image-webp/assets/291257/00ce71d8-4476-4a27-9562-2cec69512094)

Github won't let me upload WebP images directly, so here are some diverging images as an archive: 
[image-webp-divergenes-3b1fbcf2ae-top.tar.gz](https://github.com/image-rs/image-webp/files/14325138/image-webp-divergenes-3b1fbcf2ae-top.tar.gz)

**Comment by fintelia** [comment]
When I investigated this before, I got as far as making a 1x1 repo in #49 but wasn't able to figure out what was going on.
