### ISSUE TITLE
Webp sometimes creates Error: Truncated data detected when parsing chunk payload depending on upstream resizing.

### ISSUE THREAD

**Issue by joshchernoff** [image-rs/image-webp#56]
Hello :wave: 

I have this little side project I've been playing with where I build a wasm application from this rust app. 
https://github.com/joshchernoff/rusty-image-resizer/blob/web/src/lib.rs

You can see I'm using image's resize_to_fill here https://github.com/joshchernoff/rusty-image-resizer/blob/696b8ef2f182d4deb45dbf074a1c3bd9356c622f/src/lib.rs#L8 and later I write to the cursor with the selected format here
https://github.com/joshchernoff/rusty-image-resizer/blob/696b8ef2f182d4deb45dbf074a1c3bd9356c622f/src/lib.rs#L23

When using `image::ImageFormat::WebP` sometimes I will produce an error in the image output. 

using the `-diag` option of the webpinfo command https://developers.google.com/speed/webp/docs/webpinfo

I produce 
```
❯ webpinfo -diag /home/somepath/resized-image.webp 
File: /home/somepath/resized-image.webp 
RIFF HEADER:
  File size:  10631
Warning: RIFF size is smaller than the file size.
Error: Truncated data detected when parsing chunk payload.
Errors detected.
There were 1 warning(s).
```

This happens as a result of the resizing because it only happens at some given sizes where I guess there is a fraction getting dropped on the floor. 

The filter also seems to play a role in this issue too. 

Thoughts?

**Comment by joshchernoff** [comment]
I've updated to see the reflected changes. 

https://github.com/joshchernoff/rusty-image-resizer/blob/dd64999664a27a773b7e122e14a2e478ac68c9f3/Cargo.toml#L9-L10

I confirmed the hash #3bd5eb2a8c09d
```
[[package]]
name = "image-webp"
version = "0.1.0"
source = "git+https://github.com/image-rs/image-webp?branch=main#3bd5eb2a8c09dcdcd04c3f7c931e7831e84adb74"
dependencies = [
 "byteorder",
 "thiserror",
]
```

Though I'm still seeing the 
```
RIFF HEADER:
  File size:  20943
Warning: RIFF size is smaller than the file size.
Error: Truncated data detected when parsing chunk payload.
Errors detected.
There were 1 warning(s).
```

you can view this yourself at https://greed.observer/rusty-image-resizer/

If you pick webp and nearest and scale to say something like 100x100.

**Comment by fintelia** [comment]
If you check `cargo tree`, I think you'll find you actually have _two_ copies of image-webp. One from crates.io and the other from github. Please try:

```toml
[patch.crates-io]
image-webp = { git = "https://github.com/image-rs/image-webp", branch = "main" }
```
