### ISSUE TITLE
Consider removing `thiserror`

### ISSUE THREAD

**Issue by RazrFalcon** [image-rs/image-webp#66]
It's a pretty heavy dependency thanks to proc-macros. By removing it we could improve compilation times and `cargo vendor` archive size.
I plan to use this library in [resvg](https://github.com/RazrFalcon/resvg) and I care about bloat quite a lot.

**Comment by kornelski** [comment]
quick-error is a good replacement IMHO. It has superset of thiserror's functionality, but uses macro_rules

**Comment by fintelia** [comment]
I'll look into switching to quick-error. Would be nice to avoid proc macros
