### ISSUE TITLE
Regression: Image no longer decoded correctly

### ISSUE THREAD

**Issue by sophie-h** [image-rs/image-webp#81]
This image

[tiny.zip](https://github.com/user-attachments/files/16256914/tiny.zip)

should be decoded as

![out](https://github.com/user-attachments/assets/0d1817f4-b950-4839-8629-9f96f8e43ae2)

but since 768b16b70b5a1d1315dda29ccc3777761a9b5a31 it seems to be decoded as

![out](https://github.com/user-attachments/assets/2220a73b-818d-4be4-b108-550c7fb575f4)

Feel free to use the images under any license.

**Comment by fintelia** [comment]
Thanks for reporting! Seems to have been an issue in the color transform code
